### ISSUE TITLE
Shutting down Maven repo

### ISSUE THREAD

**Issue by Stealth2800** [mkremins/fanciful#83]
Just an FYI to anyone still using Fanciful in any of their projects - my Maven repo (repo.stealthyone.com) has been shut down.  I would recommend moving to Spigot's [ChatComponent API ](https://www.spigotmc.org/wiki/the-chat-component-api/)

**Comment by itsaphel** [comment]
Just noticed today when a build was errored out.

@kashike 's [Text ](https://github.com/KyoriPowered/text) is probably my recommend. It's much more elegant than the Spigot ChatComponent API (which, frankly, I think is trash).

Is there an archive of builds we can use locally so we don't have to move over to something new quicker?

**Comment by mkremins** [comment]
Thanks for the notice @Stealth2800, and for hosting the artifacts as long as you did! I've [updated the readme](https://github.com/mkremins/fanciful/commit/ed870f3a19810b5c96ad91ee784e67a83260c7ed) to reflect the closure of the Maven repo and the largely outdated/inactive status of the project as a whole. I'll leave this issue open for now so that anyone who's wondering about the Maven repo can figure out what's going on.

**Comment by markhughes** [comment]
@itsaphel thanks for sharing! What a beautiful library :)
